services:
  - type: web
    name: tamr-store
    runtime: python
    pythonVersion: 3.11  # ← هذه أهم سطر لحل الخطأ
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tamr_store_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://db_tamr_store_project_v7os_user:fEQDGKSgHuHN5UTiLRne30FLLvwbrv6k@dpg-d1ccasuuk2gs73aisflg-a.oregon-postgres.render.com/db_tamr_store_project_v7os
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
