services:
  - type: web
    name: tamr-store
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tamr_store_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY
      - key: DEBUG
        value: "False"
