# Generated by Django 5.2.3 on 2025-06-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplemodel',
            options={'verbose_name': 'نموذج', 'verbose_name_plural': 'النماذج'},
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
    ]
