# Generated by Django 5.2.3 on 2025-06-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_samplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التاجر أو الشركة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية المطلوبة (كجم)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
            ],
            options={
                'verbose_name': 'طلب جملة',
                'verbose_name_plural': 'طلبات الجملة',
            },
        ),
    ]
