# Generated by Django 5.2.3 on 2025-06-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bulkorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkorder',
            name='name',
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, verbose_name='البريد الإلكتروني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='full_name',
            field=models.CharField(default='اسم افتراضي', max_length=100, verbose_name='اسم التاجر أو الشركة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='رقم الجوال'),
            preserve_default=False,
        ),
    ]
